### ISSUE TITLE
Timeframe and last improvements

### ISSUE THREAD

**Issue by vongohren** [Fralleee/diwala-frontend-challenge#8]
Hey! Just wondering what you want to have as a timeframe. Im comfortable doing Monday based on the most action of the repo is from monday, even if you initialized stuff 7 days ago.

Also, what do you want to achive before saying you are done?

Anything that you feel is missing or you want to summarize and end to this?

**Comment by Fralleee** [comment]
Hey!
Excellent question :)

I would consider the assignment as "done" when the ordering logic is complete. Collecting pizzas into one order and placing the order (saving into DB). As well as being able to fetch the users' order history and displaying that appropriately.

That said, I would like to apply some polish (style and UX):
- Adding stuff like tab index, alt-text e.t.c. where it's supposed to be according to HTML-guidelines.
- Add more animations in the same style when the webpage is interacted with for consistency e.g. button clicks, hover.
- Improve the responsive layout. Currently, the page is not optimal when viewed with mobile devices.
- Style clean up, moving certain css values into variables and shared imports.

Stuff that I will consider out of scope but in a longer time frame SHOULD be done:
- Add typescript
- More tests
- Profiling and performance optimizations

**Comment by vongohren** [comment]
Sweet! Nice summary and we will set the timeline for this to be Sunday then. 
I will continesly look and ask questions, but the weekend might go to other things.
So I asked for a review time to be set from Tuesday and onwards next week - #9
